# Site
name: "Dmove Blog"
title: "Welcome!"
description: "기술과 문화 그리고 다양한 소식들을 공유합니다."
logo: 'assets/images/Dmove.png'
favicon: 'assets/images/banners/favicon.ico'
baseurl: 
google_analytics: 'UA-46278016-1'
disqus: 'demowebsite'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]


# Authors
authors:

  jenna:
    name : Jenna
    display_name : Jenna
    executive : Marketing Manager
    avatar : 'assets/images/main/img_ourteam_jenna.png'
    email : jenna@dmove.kr
    description : 디무브 Sales & Marketing Manager Jenna 입니다.
    web : https://www.dmove.co.kr/company/our-team#jenna

  
  hailey:
    name : hailey
    display_name : Hailey
    executive : Marketing Manager
    avatar : 'assets/images/main/img_ourteam_Hailey.png'
    email : jenna@dmove.kr
    description : 디무브 Sales & Marketing Manager hailey 입니다.
    web : https://www.dmove.co.kr/company/our-team#hailey

  sarah:
    name : Sarah
    display_name : Sarah
    executive: Sales Support
    avatar : 'assets/images/main/img_ourteam_sarah.png'
    email : jenna@dmove.kr
    description : 디무브 Sales Admin 업무를 수행하고 있는 sarah 입니다.
    web : https://www.dmove.co.kr/company/our-team#sarah


  ellin:
    name : Ellin
    display_name : Ellin
    executive : Office Manager
    avatar : 'assets/images/main/img_ourteam_ellin.png'
    email : ellin@dmove.kr
    description : 디무브 Office Manager Ellin 입니다.
    web : https://www.dmove.co.kr/company/our-team#ellin


  andy:
    name : Andy
    display_name : Andy
    executive : Sr.Solution Engineer
    avatar : 'assets/images/main/img_ourteam_andy.png'
    email : wign21@dmove.kr
    description : 디무브 Atlassian Solution Engineer Andy 입니다.
    web : https://www.dmove.co.kr/company/our-team#andy 

    
  
  jackson:
    name : Jackson
    display_name : Jackson
    executive : Solution Engineer
    avatar : 'assets/images/main/img_ourteam_jackson.png'
    email : jackson@dmove.kr
    description : 디무브 Atlassian Solution Engineer Jackson 입니다.
    web : https://www.dmove.co.kr/company/our-team#jackson

  ethan:
    name : Ethan
    display_name : Ethan
    executive : Solution Engineer
    avatar : 'assets/images/main/img_ourteam_ethan.png'
    email : ethan@dmove.kr
    description : 디무브 아틀라시안 개발자로 근무하고 있습니다. 블로그 많이 사랑해 주세요!
    web : https://www.dmove.co.kr/company/our-team#ethan

  eddie:
    name : Eddie
    display_name : Eddie
    executive : Solution Engineer
    avatar : 'assets/images/main/img_ourteam_eddie.png'
    email : eddie@dmove.kr
    description : 디무브 Atlassian Solution Engineer Eddie 입니다.
    web : https://www.dmove.co.kr/company/our-team#eddie 

  ray:
    name : Ray
    display_name : Ray
    executive : Solution Engineer
    avatar : 'assets/images/main/img_ourteam_Ray.png'
    email : eddie@dmove.kr
    description : 디무브 Solution Engineer Ray 입니다.
    web : https://www.dmove.co.kr/company/our-team#ray
  
  

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-toc
  - jekyll-glossary_tooltip
  - jemoji
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 9
paginate_path: /page:num/
    
# Other
markdown: kramdown

#다크 모드 추가
dark_theme_toggle : true




kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
